project:
  type: book
  output-dir: docs
book:
  title: "{{< latex >}} Dersleri"
  author: "Zafer ACAR"
  date: 2022-03-06
  date-format: "DD/MM/YYYY"
  lang: tr

  #page-footer: 
    #left: "[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.tr)"

  

  chapters:
    - index.qmd
    - 01-temeller.qmd
    - 02-ilkadimlar.qmd
    - 03-dizgi.qmd
    - 04-matematik.qmd
    - 05-yuzergezer.qmd
    - 06-ozelsayfalar.qmd
    - 07-ozellestirmeler.qmd
    - 08-kaynakca.qmd
  search: true
  repo-url: https://github.com/acarzfr/latex-dersleri/
  #repo-actions: [edit]
  downloads: [pdf]
  sharing: [twitter, linkedin]
  
bibliography: references.bib

format:
  html:
    theme: sandstone
     # light: sandstone
     # dark: solar
    html-math-method: katex
    lang: tr
    include-in-header: preamble.html
    

    filters:
     - lightbox
     - latex-environment
    environments: [center]
    lightbox: auto
     
  pdf:
    documentclass: scrreprt
    include-in-header: preamble.tex
      #fontfamily: libertinus

google-analytics: "G-HDQ76YF4X3"

editor: visual