project:
  type: book
  output-dir: docs
book:
  title: "{{< latex >}} Dersleri"
  author: "Zafer ACAR"
  date: 2022-03-06
  date-format: "DD/MM/YYYY"
  language: tr
  


  #page-footer: 
    #left: "[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.tr)"

  

  chapters:
    - index.qmd
    - 01-temeller.qmd
    - 02-ilkadimlar.qmd
    - 03-dizgi.qmd
    - 04-matematik.qmd
    - 05-yuzergezer.qmd
    - 06-ozelsayfalar.qmd
    - 07-ozellestirmeler.qmd
    - 08-kaynakca.qmd
  search: true
  repo-url: https://github.com/acarzfr/latex-dersleri/
  #repo-actions: [edit]
  downloads: [pdf]
  sharing: [twitter, linkedin]
  
bibliography: references.bib

format:
  html:
    theme: cosmo
     # light: sandstone
     # dark: solar
    html-math-method: katex
    lang: tr
    language:
      tr:
        crossref-nte-title: "Not"
        crossref-nte-prefix: "Not"
        crossref-wrn-title: "Uyarı"
        crossref-wrn-prefix: "Uyarı"
 
        
    include-in-header: preamble.html
    lightbox: true
    mainfont: "Atkinson Hyperlegible"
    toc-expand: true
    
    

    filters:
     - latex-environment
     - shinylive
    environments: [center]
   
     
  pdf:
    documentclass: scrreprt
    include-in-header: preamble.tex
      #fontfamily: libertinus
    lang: tr
   
    
    

    
    



editor: source