project:
  type: book
  output-dir: docs
book:
  title: "LaTeX Dersleri"
  author: "Zafer ACAR"
  date: 2022-03-06
  date-format: "DD/MM/YYYY"
  #page-footer: 
    #left: "[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.tr)"

  

  chapters:
    - index.qmd
    - temeller.qmd
    - ilkadimlar.qmd
    - dizgi.qmd
    - matematik.qmd
    - ozelsayfalar.qmd
    - ozellestirmeler.qmd
    - kaynakca.qmd
  search: true
  repo-url: https://github.com/acarzfr/latex-dersleri/
  #repo-actions: [edit]
  downloads: [pdf]
  sharing: [twitter, linkedin]
  
bibliography: references.bib

format:
  html:
    theme: sandstone
     # light: sandstone
     # dark: solar
    lang: tr
    include-in-header: preamble.html
    filters:
     - lightbox
     - latex-environment
    environments: [center]
    lightbox: auto
     
  pdf:
    documentclass: scrreprt
    include-in-header: preamble.tex
      #fontfamily: libertinus

editor: visual

