# Sunuş {.unnumbered}


Bu kitap, artık aktif olmayan <https://texdizgi.com/> adresinde yazmış olduğum yazıların derlenmesiyle ortaya çıktı. Aslında oradaki yazılar da {{< latex >}}'le ilgili yazmaya başladığım ve bir türlü sonunun getiremediğim kitabın tamamlanmış bölümlerinin ürünüydü. 

Kitabı doğal olarak {{< latex >}}'le yazıyordum. [RMarkdown](https://rmarkdown.rstudio.com/) ve [Quarto](https://quarto.org/) ile tanıştıktan sonra kitabı yalnızca PDF olarak değil, etkileşime izin vermesi ve daha bir çok avantajından  dolayı HTML olarak da dağıtmaya karar verdim. 

Kitap etkileşimli hale [TeXLive.net](https://texlive.net/) sayesinde geldi. Etkileşimden faydalanmak istiyorsanız internet bağlantınız olduğunda HTML sürümünü kullanmanız önerilir. Bu sayede kendi denemelerinizi yapabilirsiniz.  

```latex
\documentclass{article}
\begin{document}
  Merhaba \LaTeX!
\end{document}
```

Yukarıdaki "Overleaf'ta açın" düğmesine bastığınızda örnek belge [Overleaf](https://www.overleaf.com/)'ta açılacak. Tabi bunun için bir hesabınız olması gerekir. "Derle" düğmesine bastığınızda ise {{< latex >}} çıktısı ile  "Çıktıyı Sil" düğmesi görünecek.^[Tüm bu düğmelerin PDF sürümde olmayacağını unutmayın.]

Kitabın taslak aşamasında ve eksik birçok konu var. Ayrıca  hatalar olabileceğini de unutmayınız. Keyifli okumalar.






